version: "3"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    image: ports-service:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
