version: "3"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  tests:
    build:
      context: .
      dockerfile: build/Dockerfile_test
    env_file:
      - .env
    command: go test -v ./...
    depends_on:
      - redis